### PR TITLE
plugin trigger when service is linked/unlinked

### PR DESCRIPTION
**Pull request by pltchuong**

### CODE REVIEW

**Comment by josegonzalez** [comment]
@pltchuong this needs a rebase, can you do that?

**Comment by pltchuong** [comment]
this is the first time i have done rebasing so pls check if I have done correctly

**Comment by josegonzalez** [comment]
There is now a `service-action` trigger in this (and other plugins). Thanks for the initial idea!

**Comment by josegonzalez** [comment]
Update: the `service-action` trigger was insufficient as implemented and did not point out which service type was being manipulated. This should now correspond to the plugin prefix (so `couchdb` or `graphite`) as the first argument.

Anyone implementing the `service-action` trigger should take this into account going forward (it's a breaking change, but hopefully not too many users are impacted).

**Pull request closed without merging**
